/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Area: typeof import('./src/components/basic/area.vue')['default']
    Basic: typeof import('./src/components/basic/index.vue')['default']
    Core: typeof import('./src/components/core/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Floor: typeof import('./src/components/basic/floor.vue')['default']
    FloorArea: typeof import('./src/components/basic/floorArea.vue')['default']
    Login: typeof import('./src/components/core/login.vue')['default']
    PhoneNumLogin: typeof import('./src/components/basic/phoneNumLogin.vue')['default']
    PwdLogin: typeof import('./src/components/basic/pwdLogin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
